### ISSUE TITLE
Question about the EffectivePeriod class

### ISSUE THREAD

**Issue by trieunguyen87** [projectbarbel/barbelhisto-core#4]
Hi,

I have been having a lot of fun experimenting with the BarbelHisto library.  I am very impressed with how easy it is to use this library and all the powerful functionality that it provides.  However, I am curious as to why the EffectivePeriod class uses the LocalDate object from Java Time, which from my understanding, is limited to year-month-day.  It seems like this limits the library in a lot of potential real world applications. For example, dealing with data that may have a short effective period such as a few hours. If that data changes states a few times within the same day, this library would not be able to query specifically for one of those effective periods. I would only be able to query for that entire day which would always just give me the last active state of that data for that specific day.

Any insights would be much appreciated. Thanks!

**Comment by nschlimm** [comment]
Hi, thanks for your question. The short answer is that when I developed the library the requirement was that effective periods are on „day granularity“. However, I have thought about making effective periods more fine grained as well and I‘m happy to see that there is a requirement for that. So I will plan to implement „finer grained effective time“ for future releases. Cheers, Niklas

**Comment by nschlimm** [comment]
The date time functionality is in progress and is already in the master branch. I am going to release asap.

**Comment by nschlimm** [comment]
Date time functionality is now released in Version 2.0
