### ISSUE TITLE
Retrieve all documents effective now

### ISSUE THREAD

**Issue by vdurbha** [projectbarbel/barbelhisto-core#7]
Can anyone help me how I can retrieve all documents which are effective now (current time)? Something like the following.

`core.retrieve(BarbelQueries.effectiveNowAll());`

**Comment by nschlimm** [comment]
Hi,
you could create your own static query class and add this method:
`    public static <T> Query<T> allActive() {
        return (Query<T>) equal(STATE, BitemporalObjectState.ACTIVE);
    }
`
Notice that if you have lots of objects in your collection, then such queries can massively impact your JVM heap memory.
Cheers, Niklas
PS: leave a star for BarbelHisto if you like it :-)

**Comment by vdurbha** [comment]
I wrote the following two methods to do what I want them to do. It appears that they're working fine. I'll have to test them more thoroughly.

```
public static <T> Query<T> allEffectiveNow() {
        return (Query<T>) QueryFactory.and(
                allActive(),
                QueryFactory.lessThanOrEqualTo(
                        BarbelQueries.EFFECTIVE_FROM,
                        BarbelHistoContext.getBarbelClock().now().withZoneSameInstant(ZoneId.systemDefault()).toInstant().toEpochMilli()),
                QueryFactory.greaterThan(
                        BarbelQueries.EFFECTIVE_UNTIL,
                        BarbelHistoContext.getBarbelClock().now().withZoneSameInstant(ZoneId.systemDefault()).toInstant().toEpochMilli()));
    }
```

```
public static <T> Query<T> allEffectiveAt(ZonedDateTime zonedDateTime) {
        return (Query<T>) QueryFactory.and(
                allActive(),
                QueryFactory.lessThanOrEqualTo(
                        BarbelQueries.EFFECTIVE_FROM,
                        zonedDateTime.toInstant().toEpochMilli()),
                QueryFactory.greaterThan(
                        BarbelQueries.EFFECTIVE_UNTIL,
                        zonedDateTime.toInstant().toEpochMilli()));
    }
```

**Comment by nschlimm** [comment]
Notice: State must be „active“ so that you do not get inactivated records from your query. You need to add that to your query criteria.
