### ISSUE TITLE
Delete a record (make it ineffective from now to infinity)

### ISSUE THREAD

**Issue by vdurbha** [projectbarbel/barbelhisto-core#8]
Is it possible to soft delete a record permanently? Lets say I have two customers and one of them is not a customer anymore. So it should not appear in future queries. How do I accomplish that?

I tried saving a new version with end date as now. But it didn't work for me.

**Comment by nschlimm** [comment]
Deletion with bitemporal data is accomplished bei adding a status field to the business object. Then you set that status to „deleted“ and save the object with effective from now to infinite. When you query all effective you exclude the objects that have status=deleted.

**Comment by nschlimm** [comment]
Can we close this one?

**Comment by vdurbha** [comment]
Yes this issue and the previous one can both be closed. Thank you for your prompt responses.
